kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: db-migration
  namespace: e89443-tools
  labels:
    component: db-migration
    created-by: jeremy.foster
    managed-by: kustomize
    name: database
    part-of: hsb
    version: 1.0.0
spec:
  lookupPolicy:
    local: false
  tags:
    - name: dev
      annotations: null
      from:
        kind: DockerImage
        name: >-
          artifacts.developer.gov.bc.ca/github-docker-remote/bcgov/hsb-dashboard/db-migration:dev
      importPolicy:
        scheduled: true
        importMode: Legacy
      referencePolicy:
        type: Source
    - name: latest
      annotations: null
      from:
        kind: DockerImage
        name: >-
          artifacts.developer.gov.bc.ca/github-docker-remote/bcgov/hsb-dashboard/db-migration:latest
      importPolicy:
        scheduled: true
        importMode: Legacy
      referencePolicy:
        type: Source
    - name: test
      annotations: null
      from:
        kind: DockerImage
        name: >-
          artifacts.developer.gov.bc.ca/github-docker-remote/bcgov/hsb-dashboard/db-migration:test
      importPolicy:
        scheduled: true
        importMode: Legacy
      referencePolicy:
        type: Source
