---
# Keycloak configuration
kind: ConfigMap
apiVersion: v1
metadata:
  name: api
  namespace: default
  annotations:
    description: API configuration
  labels:
    name: api
    part-of: hsb
    version: 1.0.0
    component: api
    managed-by: kustomize
    created-by: jeremy.foster
type: Opaque
data:
