---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: enable-api-to-internet
  labels:
    name: enable-api-to-internet
    part-of: hsb
    version: 1.0.0
    component: api
    managed-by: kustomize
    created-by: jeremy.foster
  annotations:
    description: Enable the api to communicate with the internet
spec:
  egress:
    - to:
        - ipBlock:
            cidr: 142.34.229.249/32
        - ipBlock:
            cidr: 142.34.94.249/32
      ports:
        - port: 8080
          protocol: TCP
  podSelector:
    matchLabels:
      part-of: hsb
      component: api
  policyTypes:
    - Egress
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: enable-api-to-database
  labels:
    name: enable-api-to-database
    part-of: hsb
    version: 1.0.0
    component: api
    managed-by: kustomize
    created-by: jeremy.foster
  annotations:
    description: Enable the api to communicate with the database
spec:
  egress:
    - to:
        - ipBlock:
            cidr: 10.99.8.2/32
        - ipBlock:
            cidr: 10.99.8.9/32
      ports:
        - port: 5432
          protocol: TCP

  podSelector:
    matchLabels:
      part-of: hsb
      component: api
  policyTypes:
    - Egress
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: enable-api-to-keycloak
  labels:
    name: enable-api-to-keycloak
    part-of: hsb
    version: 1.0.0
    component: api
    managed-by: kustomize
    created-by: jeremy.foster
  annotations:
    description: Enable the api to communicate with the keycloak
spec:
  egress:
    - to:
        - ipBlock:
            cidr: 142.34.229.4/32 # Gold cluster *.apps IP
        - ipBlock:
            cidr: 142.34.64.4/32 # Gold DR cluster *.apps IP in case SSO fails over
      ports:
        - protocol: TCP
          port: 443
  podSelector:
    matchLabels:
      part-of: hsb
      component: api
  policyTypes:
    - Egress
