---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: e89443-dev

resources:
  - ../../secrets/dev
  - ../../../base/data-service
  - ../../../base/config

patches:
  - target:
      kind: ConfigMap
      name: keycloak
    patch: |-
      - op: replace
        path: /data/KEYCLOAK_DEBUG
        value: "true"
      - op: replace
        path: /data/KEYCLOAK_AUTHORITY
        value: https://dev.loginproxy.gov.bc.ca/auth/realms/standard
      - op: replace
        path: /data/KEYCLOAK_AUDIENCE
        value: hsb-dashboard-5128
      - op: replace
        path: /data/KEYCLOAK_ISSUER
        value: hsb-dashboard-5128
  - target:
      kind: ConfigMap
      name: ches
    patch: |-
      - op: replace
        path: /data/AUTH_URL
        value: https://dev.loginproxy.gov.bc.ca/auth/realms/comsvcauth/protocol/openid-connect/token
      - op: replace
        path: /data/HOST_URI
        value: https://ches-dev.api.gov.bc.ca/api/v1
      - op: replace
        path: /data/FROM
        value: (DEV) Hosting Service Dashboard <hsb@gov.bc.ca>
      - op: replace
        path: /data/TO
        value: jeremy.foster@fosol.ca
