apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline
  namespace: e89443-dev
  labels:
    name: pipeline
    part-of: hsb
    version: 1.0.0
    component: pipeline
    managed-by: kustomize
    created-by: jeremy.foster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pipeline
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: e89443-tools
