export const tableRowData = [
  {
    server: 'Server Alpha',
    tenant: '',
    os: 'Ubuntu 20.04 LTS',
    allocated: 10.0,
    unused: 2.0,
  },
  {
    server: 'Server Beta',
    tenant: '',
    os: 'Red Hat Enterprise Linux',
    allocated: 16.0,
    unused: 1.0,
  },
  {
    server: 'Server Gamma',
    tenant: '',
    os: 'Windows Server 2019',
    allocated: 8.0,
    unused: 4.0,
  },
  {
    server: 'Server Delta',
    tenant: '',
    os: 'CentOS 7',
    allocated: 20.0,
    unused: 10.0,
  },
  {
    server: 'Server Epsilon',
    tenant: '',
    os: 'Debian 10',
    allocated: 12.5,
    unused: 3.5,
  },
  {
    server: 'Server Zeta',
    tenant: '',
    os: 'SUSE Linux Enterprise Server',
    allocated: 25.0,
    unused: 5.0,
  },
  {
    server: 'Server Delta',
    tenant: '',
    os: 'CentOS 7',
    allocated: 20.0,
    unused: 10.0,
  },
  {
    server: 'Server Epsilon',
    tenant: '',
    os: 'Debian 10',
    allocated: 12.5,
    unused: 3.5,
  },
  {
    server: 'Server Zeta',
    tenant: '',
    os: 'SUSE Linux Enterprise Server',
    allocated: 25.0,
    unused: 5.0,
  },  {
    server: 'Server Epsilon',
    tenant: '',
    os: 'Debian 10',
    allocated: 12.5,
    unused: 3.5,
  },
  {
    server: 'Server Zeta',
    tenant: '',
    os: 'SUSE Linux Enterprise Server',
    allocated: 25.0,
    unused: 5.0,
  },
  {
    server: 'Server Delta',
    tenant: '',
    os: 'CentOS 7',
    allocated: 20.0,
    unused: 10.0,
  },
  {
    server: 'Server Epsilon',
    tenant: '',
    os: 'Debian 10',
    allocated: 12.5,
    unused: 3.5,
  },
  {
    server: 'Server Zeta',
    tenant: '',
    os: 'SUSE Linux Enterprise Server',
    allocated: 25.0,
    unused: 5.0,
  },
];

export default tableRowData;
