---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: e89443-dev

resources:
  - ../../../base/database

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: database
    envs:
      - database.env
  - name: database-local
    envs:
      - database-local.env
