kind: ConfigMap
apiVersion: v1
metadata:
  name: dashboard
  namespace: default
  annotations:
    description: Dashboard application configuration
  labels:
    name: dashboard
    part-of: hsb
    version: 1.0.0
    component: app
    managed-by: kustomize
    created-by: jeremy.foster
data:
  NEXTAUTH_URL: https://dev-hsb.apps.emerald.devops.gov.bc.ca/
