CREATE OR REPLACE VIEW "vFileSystemHistoryItem" AS
SELECT
    "Id"
    , "ServiceNowKey"
    , "Name"
    , "Label"
    , "Category"
    , "Subcategory"
    , "StorageType"
    , "MediaType"
    , "VolumeId"
    , "ClassName"
    , "Capacity"
    , "DiskSpace"
    , "Size"
    , "SizeBytes"
    , "UsedSizeBytes"
    , "AvailableSpace"
    , "FreeSpace"
    , "FreeSpaceBytes"
    , "CreatedOn"
    , "CreatedBy"
    , "UpdatedOn"
    , "UpdatedBy"
    , "Version"
    , "ServerItemServiceNowKey"
    , "InstallStatus"
FROM public."FileSystemHistoryItem";
