---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: e89443-dev

resources:
  - ../../base

patches:
  # - target:
  #     kind: PostgresCluster
  #     name: .*
  #   patch: |-
  #     - op: replace
  #       path: /metadata/name
  #       value: tno-cluster
