kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: api
  namespace: e89443-tools
  labels:
    component: api
    created-by: jeremy.foster
    managed-by: kustomize
    name: api
    part-of: hsb
    version: 1.0.0
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      annotations: null
      from:
        kind: DockerImage
        name: >-
          artifacts.developer.gov.bc.ca/github-docker-remote/bcgov/bcgov/hsb-dashboard/api:latest
      generation: 1
      importPolicy:
        scheduled: true
        importMode: Legacy
      referencePolicy:
        type: Source
