---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: e89443-dev

resources:
  - ../../../base/jobs

patches:
  - target:
      kind: Job
      name: data-service
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: image-registry.apps.emerald.devops.gov.bc.ca/e89443-tools/data-service:dev
