apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline
  namespace: default
  labels:
    name: pipeline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pipeline
  namespace: default
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: e89443-tools
