kind: Job
apiVersion: batch/v1
metadata:
  name: data-service
  generateName: data-service-
  namespace: default
  labels:
    managed-by: kustomize
    name: data-service
    DataClass: Low
    part-of: hsb
    version: 1.0.0
    created-by: jeremy.foster
    component: service
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 6
  # selector:
  #   matchLabels:
  #     controller-uid: 3670f1e1-3414-4009-829f-bf4a4fdbbca7
  template:
    metadata:
      creationTimestamp: null
      labels:
        managed-by: kustomize
        name: data-service
        DataClass: Low
        part-of: hsb
        version: 1.0.0
        created-by: jeremy.foster
        component: service
    spec:
      containers:
        - name: data-service
          image: >-
            image-registry.apps.emerald.devops.gov.bc.ca/e89443-tools/data-service:dev
          env:
            # - name: Service__Actions__0
            #   value: clean-organizations
            - name: Logging__LogLevel__HSB
              value: Debug
            - name: HTTP_PROXY
              value: "http://swpxkam.gov.bc.ca:8080"
            - name: HTTPS_PROXY
              value: "http://swpxkam.gov.bc.ca:8080"
            - name: NO_PROXY
              value: >-
                .cluster.local,.svc,10.91.0.0/16,172.30.0.0/16,127.0.0.1,localhost,.gov.bc.ca,api
            - name: Keycloak__Authority
              valueFrom:
                configMapKeyRef:
                  name: keycloak
                  key: KEYCLOAK_AUTHORITY
            - name: Keycloak__Audience
              valueFrom:
                configMapKeyRef:
                  name: keycloak
                  key: KEYCLOAK_AUDIENCE
            - name: Keycloak__Issuer
              valueFrom:
                configMapKeyRef:
                  name: keycloak
                  key: KEYCLOAK_ISSUER
            - name: Keycloak__Secret
              valueFrom:
                secretKeyRef:
                  name: keycloak
                  key: KEYCLOAK_CLIENT_SECRET
            - name: Service__ApiUrl
              valueFrom:
                configMapKeyRef:
                  name: data-service
                  key: API_URL
            - name: ServiceNow__ApiUrl
              valueFrom:
                secretKeyRef:
                  name: service-now
                  key: URL
            - name: ServiceNow__Instance
              valueFrom:
                secretKeyRef:
                  name: service-now
                  key: INSTANCE
            - name: ServiceNow__Username
              valueFrom:
                secretKeyRef:
                  name: service-now
                  key: USERNAME
            - name: ServiceNow__Password
              valueFrom:
                secretKeyRef:
                  name: service-now
                  key: PASSWORD
            - name: CHES__AuthUrl
              valueFrom:
                configMapKeyRef:
                  name: ches
                  key: AUTH_URL
            - name: CHES__HostUri
              valueFrom:
                configMapKeyRef:
                  name: ches
                  key: HOST_URI
            - name: CHES__From
              valueFrom:
                configMapKeyRef:
                  name: ches
                  key: FROM
            - name: CHES__OverrideTo
              valueFrom:
                configMapKeyRef:
                  name: ches
                  key: TO
            - name: CHES__EmailEnabled
              valueFrom:
                configMapKeyRef:
                  name: ches
                  key: EMAIL_ENABLED
            - name: CHES__EmailAuthorized
              valueFrom:
                configMapKeyRef:
                  name: ches
                  key: EMAIL_AUTHORIZED
            - name: CHES__Username
              valueFrom:
                secretKeyRef:
                  name: ches
                  key: USERNAME
            - name: CHES__Password
              valueFrom:
                secretKeyRef:
                  name: ches
                  key: PASSWORD
          resources:
            limits:
              cpu: 100m
              memory: 1Gi
            requests:
              cpu: 50m
              memory: 120Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: OnFailure
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
