---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: e89443-tools

resources:
  - ../../base/tekton/image-streams
  - ../../base/tekton/pipelines
  - ../../base/tekton/tasks
