---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: e89443-tools

resources:
  - ../../base/build

patches:
  - target:
      kind: ConfigMap
      name: api
    patch: |-
      - op: replace
        path: /data/KEYCLOAK_AUTHORITY
        value: https://dev.loginproxy.gov.bc.ca/auth/realms/standard
      - op: replace
        path: /data/CSS_ENVIRONMENT
        value: dev
      - op: replace
        path: /data/CSS_AUTHORITY
        value: https://loginproxy.gov.bc.ca
      - op: replace
        path: /data/REPORTING_SUBSCRIBER_URL
        value: https://dev.mmi.gov.bc.ca
      - op: replace
        path: /data/REPORTING_VIEW_CONTENT_URL
        value: https://dev.mmi.gov.bc.ca/view/
      - op: replace
        path: /data/REPORTING_REQUEST_TRANSCRIPT_URL
        value: https://dev.mmi.gov.bc.ca/api/subscriber/work/orders/transcribe/
  - target:
      kind: Route
      name: api-editor
    patch: |-
      - op: replace
        path: /spec/host
        value: hsb-dev.apps.silver.devops.gov.bc.ca
  - target:
      kind: Route
      name: api-editor-tls
    patch: |-
      - op: replace
        path: /spec/host
        value: dev.editor.mmi.gov.bc.ca
  # - target:
  #     kind: DeploymentConfig
  #     name: api
  #   patch: |-
  #     - op: replace
  #       path: /spec/replicas
  #       value: 3
  #     - op: replace
  #       path: /spec/template/spec/containers/0/resources/requests/cpu
  #       value: 100m
  #     - op: replace
  #       path: /spec/template/spec/containers/0/resources/requests/memory
  #       value: 150Mi
  #     - op: replace
  #       path: /spec/template/spec/containers/0/resources/limits/cpu
  #       value: 300m
  #     - op: replace
  #       path: /spec/template/spec/containers/0/resources/limits/memory
  #       value: 300Mi
  #     - op: replace
  #       path: /spec/triggers/1/imageChangeParams/from/name
  #       value: api:dev
  - target:
      kind: StatefulSet
      name: api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 75m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 450Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 100m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 1Gi
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: image-registry.openshift-image-registry.svc:5000/9b301c-tools/api:dev
